name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v5"

      - name: Set up devkit
        uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: bun

      - name: "Install dependencies"
        run: "bun install --frozen-lockfile"

      - name: "Run the code checks"
        run: "just full-check"

      - name: "Build package"
        run: "just tsc-build"

      - name: "Run tests"
        run: "just test"

      - name: "Add summary"
        run: |
          echo "## Continuous Deployment results" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
